#!/bin/zsh -x

cd $HOME
pwd
for f in `ls -d $HOME/projects/fmaritato/dot_files/.??*`
do
  filename=${f:t}
  if [ -f $f ]; then
    echo $filename
    if [ -f $HOME/$filename ]; then
      echo "File exists. Moving on..."
    elif [ -h $HOME/$filename ]; then
      echo "File exists: $HOME/$filename"
      rm $HOME/$filename
    fi
    ln -s $f $HOME/$filename
  fi
done
